#!/usr/bin/env python

import argparse
import json
import os.path as path
import os
import matplotlib.pyplot as plt
import numpy as np

library_to_color = {'YACLib': 'r', 'Folly': 'royalblue', 'Qt': 'limegreen', 'BoostThread': 'gray', 'Std': 'orange'}


def parse_args():
    """
    --src /path/to/data.json file
    --dst /path/to/pictures_folder
    """
    # TODO: improve it
    parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--src", type=str, help="result directory location", required=True)
    args = parser.parse_args()
    return args


def parse_bench_results(json_):
    benchmark_results = {}
    for bench in json_["benchmarks"]:
        bname = bench["name"].split('/')
        bname.pop()  # remove 'real_time' suffix
        bench_group = bname[0]  # benchmark group name
        if bench_group == 'Then':
            assert len(bname) == 4
            case = bname[3]
            match case:
                case '0':
                    bench_group = bench_group + 'AllInline'
                case '1':
                    bench_group = bench_group + 'OneInline'
                case '2':
                    bench_group = bench_group + 'Scheduler'
                case _:
                    raise RuntimeError
            bname.pop()
        libname = bname[1]  # library name
        bcase = '/'.join(bname[2:])  # benchmark case name (arguments)
        benchmark_results.setdefault(bench_group, {})
        benchmark_results[bench_group].setdefault(libname, {})
        benchmark_results[bench_group][libname][bcase] = bench['real_time']
    return benchmark_results


def create_dir_if_not_exists(dirname):
    try:
        os.mkdir(dirname)
    except FileExistsError:
        pass


# bench_data['lib'] -> {'': time} / {'0': time, '1': time}
def generate_picture(name, bench_data, save_path):
    picture_file = path.join(save_path, name) + '.svg'
    print(f'Generate picture: {picture_file} ...')

    libraries_count = len(bench_data)
    assert libraries_count != 0, 'empty benchmark result dictionary'
    benchmark_len = len(list(bench_data.values())[0])
    # TODO: assert that for all values bench_len is the same
    assert all(len(v) == benchmark_len for v in bench_data.values()), 'benchmark lens do not the same'

    libnumber = len(bench_data)
    width = 1
    x = np.arange(0, width * (libnumber + 1) * benchmark_len, (libnumber + 1) * width)

    fig, ax = plt.subplots(figsize=(40, 30))
    for i, libname in enumerate(bench_data.keys()):
        y = bench_data[libname].values()
        ax.bar(x + i * width, y, width, linewidth=1, label=libname, color=library_to_color[libname])

    ax.set(xticks=np.arange(0, 0))
    ax.set_title(name, fontsize='64')
    ax.set_ylabel('time', fontsize='48')
    ax.tick_params(direction='out', labelsize='30')
    ax.legend(prop={'size': 40}, loc='lower right')
    plt.savefig(picture_file)
    plt.clf()
    plt.close(fig)


# bench_results: dict [BenchGroupName][LibraryName]["X arg"] -> Time ("Y arg")
def draw_bench_results(bench_results, save_path):
    save_path = path.join(save_path, 'picture')
    create_dir_if_not_exists(save_path)
    for bench_group, results in bench_results.items():
        generate_picture(bench_group, results, save_path)


def main():
    args = parse_args()
    for cur_dir, subdirs, files in os.walk(args.src):
        if 'data.json' in files:
            bench_filename = path.join(cur_dir, 'data.json')
            print(f'Parse pictures: {bench_filename}')
            with open(bench_filename) as f:
                json_ = json.load(f)
            benchmark_results = parse_bench_results(json_)
            save_path = cur_dir
            draw_bench_results(benchmark_results, save_path)


if __name__ == '__main__':
    main()
